apiVersion: v1
kind: Service
metadata:
  name: http-server-service
spec:
  ports:
  - nodePort: 30001
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: http-server-example
  sessionAffinity: None
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server
spec:
  selector:
    matchLabels:
      run: http-server-example
  replicas: 1
  template:
    metadata:
      labels:
        run: http-server-example
    spec:
      containers:
        - name: http-server
          image: python-http-server
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              protocol: TCP