apiVersion: v1
kind: Service
metadata:
  name: http-server-service
spec:
  ports:
  - port: 5000
    protocol: "TCP"
    targetPort: 5000
  selector:
    run: http-server-example
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server
spec:
  selector:
    matchLabels:
      run: http-server-example
  replicas: 1
  template:
    metadata:
      labels:
        run: http-server-example
    spec:
      containers:
        - name: http-server
          image: python-http-server
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
              protocol: TCP